<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>analystclick</name>
   <tag></tag>
   <elementGuidId>1798e0f5-9c42-46b2-ab29-d2ef5abaf8d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tbl-reportlist&quot;]/tbody/tr[2]/td/div/div/table/tbody/tr[2]/td/div/div[1]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
