<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickexceldart</name>
   <tag></tag>
   <elementGuidId>7797ce50-9970-4a0e-b966-9a3f3ae9be6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tbl-reportlist&quot;]/tbody/tr[2]/td/div/div/table/tbody/tr[2]/td/div/div[1]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
