<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>retaildashboard</name>
   <tag></tag>
   <elementGuidId>29665b44-72dd-4086-a73b-3b09f646d541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;form1&quot;]/div[3]/div[2]/div[1]/div/div[1]/div[2]/div/div/div/div/div[2]/div/div/div/div[2]/div[1]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
